#!/bin/bash

# Check credential directory
if [ -z "$CREDENTIALS_DIRECTORY" ]; then
    echo "Error: missing CREDENTIALS_DIRECTORY env" >&2
    exit 1
fi

# Load url from credential directory
URL_FILE="$CREDENTIALS_DIRECTORY/cronitor.url"
if ! [ -f "$URL_FILE" ]; then
    echo "Error: missing cronitor.url" >&2
    exit 2
else
    URL="$(< "$URL_FILE")"
fi

# Check if url is valid
if ! [[ "$URL" =~ ^http(s)?://.* ]]; then
    echo "Error: invalid url" >&2
    exit 4
fi

# Check runtime directory
if [ -z "$RUNTIME_DIRECTORY" ]; then
    echo "Error: missing RUNTIME_DIRECTORY" >&2
    exit 3
fi

# Retrieve counter
counter=0
COUNTER_FILE="$RUNTIME_DIRECTORY/counter"
if [ -f "$COUNTER_FILE" ]; then
    counter="$(< "$COUNTER_FILE")"

    # validate counter
    if ! [[ "$counter" =~ ^[0-9]+$ ]]; then
        echo "Error: counter has invalid value, forcing 0" >&2
        counter=0
    fi
fi

# increment counter
(( counter++ ))

# save new counter
printf "%s\n" "$counter" > "$COUNTER_FILE"

# Retrieve error counter
error_counter=0
ERROR_COUNTER_FILE="$RUNTIME_DIRECTORY/error_counter"
if [ -f "$ERROR_COUNTER_FILE" ]; then
    error_counter="$(< "$ERROR_COUNTER_FILE")"

    # validate counter
    if ! [[ "$error_counter" =~ ^[0-9]+$ ]]; then
        echo "Error: error_counter has invalid value, forcing 0" >&2
        error_counter=0
    fi
fi

# Retrieve uptime
UPTIME="$(uptime -p)"

# Setting max time
if [ -z "$MAX_TIME" ]; then
    MAX_TIME=60
fi

# Calling curl with parameters
if curl --max-time "$MAX_TIME" \
    --silent \
    --get \
    --data-urlencode "msg=uptime: $UPTIME" \
    --data-urlencode "metric=count:$counter" \
    --data-urlencode "metric=error_count:$error_counter" \
    "$URL" > /dev/null ; then
        # resetting error_counter
        [ -f "$ERROR_COUNTER_FILE" ] && rm "$ERROR_COUNTER_FILE"
else
    # increment error_counter
    (( error_counter++ ))
    # save new error_counter
    printf "%s\n" "$error_counter" > "$ERROR_COUNTER_FILE"
fi